# Generated by Django 4.2.7 on 2024-03-02 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(default='john', max_length=30)),
                ('surname', models.CharField(default='Smith', max_length=40)),
                ('birthday', models.DateField(default=datetime.datetime(2024, 3, 2, 8, 21, 33, 297231, tzinfo=datetime.timezone.utc))),
                ('ATOM_id', models.CharField(blank=True, max_length=18)),
                ('GDPR', models.BooleanField(default=True)),
                ('healthProblems', models.CharField(default='Dítě nemá žádná zdravotní omezení ani speciální požadavky na stravu či zacházení', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres1', models.CharField(default='', max_length=255)),
                ('city1', models.CharField(default='', max_length=100)),
                ('psc1', models.CharField(default='', max_length=15)),
                ('mobile1', models.CharField(default='', max_length=13)),
                ('addres2', models.CharField(blank=True, default='', max_length=255)),
                ('city2', models.CharField(blank=True, default='', max_length=100)),
                ('psc2', models.CharField(blank=True, default='', max_length=15)),
                ('mobile2', models.CharField(default='', max_length=13)),
                ('wallet', models.FloatField(default=0.0)),
                ('position', models.IntegerField(default=0)),
                ('member', models.ManyToManyField(blank=True, related_name='member', to='Accounts.member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(default=[models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)], related_name='access_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
