# Generated by Django 4.2.7 on 2024-03-18 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 16, 27, 7, 72815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('payed_date', models.DateField(blank=True, null=True)),
                ('payment_from', models.CharField(blank=True, default='neznámý účet', max_length=35)),
                ('transaction_number', models.CharField(blank=True, max_length=30)),
                ('var_symbol', models.CharField(blank=True, max_length=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.account')),
            ],
        ),
    ]
