# Generated by Django 4.2.7 on 2024-03-20 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_member_birthday_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payed_in_cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 13, 54, 59, 889102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='var_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
